# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Track.destroy_all

User.create(username: 'Guest', password: 'password', email: 'Guest@gmail.com')
User.create(username: 'Steve', password: 'password', email: 'Steve@gmail.com')
User.create(username: 'Dylan', password: 'password', email: 'Dylan@gmail.com')
User.create(username: 'Diane', password: 'password', email: 'Diane@gmail.com')
User.create(username: 'Joe', password: 'password', email: 'Joe@gmail.com')

Track.create(user_id: 1, title: 'All We Know', artist: 'The Chainsmokers', track_url:'https://s3-us-west-1.amazonaws.com/eden-audio/tracks/01+All+We+Know+(feat.+Phoebe+Ryan).m4a', img_url: 'https://s3-us-west-1.amazonaws.com/eden-audio/track_images/the-chainsmokers-all-we-know.jpg')
Track.create(user_id: 1, title: 'Closer', artist: 'The Chainsmokers', track_url:'https://s3-us-west-1.amazonaws.com/eden-audio/tracks/01+Closer+(feat.+Halsey).m4a', img_url: 'https://s3-us-west-1.amazonaws.com/eden-audio/track_images/the-chainsmokers-closer.jpg')
Track.create(user_id: 1, title: "I Don't Mind", artist: 'Usher', track_url:'https://s3-us-west-1.amazonaws.com/eden-audio/tracks/7+-+Usher+-+I+Don_t+Mind+(ft.+Juicy+J).mp3', img_url: 'https://s3-us-west-1.amazonaws.com/eden-audio/track_images/usher-i-dont-mind.png')
Track.create(user_id: 1, title: "Five More Hours", artist: 'Deorro', track_url:'https://s3-us-west-1.amazonaws.com/eden-audio/tracks/1-04+Five+More+Hours.m4a', img_url: 'https://s3-us-west-1.amazonaws.com/eden-audio/track_images/deorro-five-more-hours.jpg')
Track.create(user_id: 1, title: "Smoke Filled Room", artist: 'Mako', track_url:'https://s3-us-west-1.amazonaws.com/eden-audio/tracks/1-08+Smoke+Filled+Room.m4a', img_url: 'https://s3-us-west-1.amazonaws.com/eden-audio/track_images/mako-smoke-filled-room.png')
Track.create(user_id: 1, title: "Stole The Show", artist: 'Kygo', track_url:'https://s3-us-west-1.amazonaws.com/eden-audio/tracks/1-02+Stole+the+Show+(feat.+Parson+James).m4a', img_url: 'https://s3-us-west-1.amazonaws.com/eden-audio/track_images/kygo-stole-the-show.jpg')

Track.create(user_id: 1, title: 'Stay', artist: 'Zedd', track_url:'https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Zedd+%E2%80%93+Stay+(Lyrics++Lyric+Video)+ft.+Alessia+Cara+%5BFuture+Bass%5D.mp3', img_url: 'https://s3-us-west-1.amazonaws.com/eden-audio/track_images/zedd-stay.jpg')
Track.create(user_id: 1, title: "I Don't Wanna Live Forever", artist: "Zayn", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/ZAYN+-+I+Don't+Wanna+Live+Forever+(Acoustic).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/zayn-dont-wanna-live-forever.jpg")
Track.create(user_id: 1, title: "TG4M", artist: "Zara", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Zara+Larsson+-+TG4M+-+Lyrics+%5BHD%5D.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/zara-tg4m.jpg")
Track.create(user_id: 1, title: "Something Just Like This", artist: "Coldplay", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/The+Chainsmokers+%26+Coldplay+-+Something+Just+Like+This.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/coldplay-something-just-like-this.jpg")
Track.create(user_id: 1, title: "Romantic (NOTD Remix)", artist: "Stanaj", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Stanaj+-+Romantic+(NOTD+Remix)+(Lyrics).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/stanaj-romantic.jpg")
Track.create(user_id: 1, title: "Bad Woman", artist: "Stanaj", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Stanaj+-+Bad+Woman.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/stanaj-bad-woman.jpg")
Track.create(user_id: 1, title: "Don't Leave", artist: "Snakehips", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Snakehips+ft.+M%C3%98+-+Don't+Leave.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/snakehips-dont-leave.jpg")
Track.create(user_id: 1, title: "Trouble", artist: "R3hab", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/R3hab+-+Trouble+Feat.+Verite+(Mp3FB.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/r3hab-trouble.jpg")
Track.create(user_id: 1, title: "Sunset Lover", artist: "Petit Biscuit", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/PETIT+BISCUIT+-+Sunset+Lover+(Mp3FB.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/petit-biscuit-sunset-lover.jpg")
Track.create(user_id: 1, title: "Kids (SeeB Remix)", artist: "One Republic", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/OneRepublic+%E2%80%93+Kids+(SeeB+Remix)+%5BPremiere%5D.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/one-republic-kids.jpg")
Track.create(user_id: 1, title: "Thinking About It (KVR Remix)", artist: "Nathan Goshen", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Nathan+Goshen+-+Thinking+About+It+(KVR+Remix)+%5BLyrics%5D.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/nathan-goshen-thinking-about-it.jpg")
Track.create(user_id: 1, title: "I Took A Pill In Ibiza", artist: "Nathan Goshen", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Nathan+Goshen+-+Thinking+About+It+(KVR+Remix)+%5BLyrics%5D.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/nathan-goshen-thinking-about-it.jpg")
Track.create(user_id: 1, title: "Scared To Be Lonely", artist: "Martin Garrix", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Martin+Garrix+%26+Dua+Lipa+-+Scared+To+Be+Lonely.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/martin-garrix-scared-to-be-lonely.jpg")
Track.create(user_id: 1, title: "Run Up", artist: "Major Lazer", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Major+Lazer+-+Run+Up+(feat.+PARTYNEXTDOOR+%26+Nicki+Minaj)+(Mp3FB.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/major-lazer-run-up.jpg")
Track.create(user_id: 1, title: "Little Do You Know", artist: "Alex & Sierra", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Little+Do+You+Know+(Alex+%26+Sierra)+(mp3goo.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/alex-sierra-little.jpg")
Track.create(user_id: 1, title: "The Other", artist: "Lauv", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/LAUV+-+The+Other+(Mp3FB.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/lauv-the-other.jpg")
Track.create(user_id: 1, title: "September Song", artist: "JP Cooper", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/JP+Cooper+-+(Acoustic)+(mp3goo.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/jp-cooper-september.jpg")
Track.create(user_id: 1, title: "It Ain't Me", artist: "Kygo", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/It+Ain%E2%80%99t+Me+-+Kygo+feat+Selena+Gomez+LYRICS.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/kygo-it-aint-me.jpg")
Track.create(user_id: 1, title: "Lighthouse (Andrelli Remix)", artist: "Hearts & Colors", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Hearts+%26+Colors+-+Lighthouse+(Andrelli+Remix)+(Mp3FB.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/hearts-colors-lighthouse.jpg")
Track.create(user_id: 1, title: "Life Goes On (NOTD Remix)", artist: "Fergie", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Fergie+-+Life+Goes+On+(NOTD+Remix).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/fergie-life-goes-on.jpg")
Track.create(user_id: 1, title: "Feels", artist: "Kiiara", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Feels+(mp3goo.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/kiiara-feels.png")
Track.create(user_id: 1, title: "Lighters", artist: "Eminen", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Eminen+Ft.+Bruno+Mars+-+Lighters+(mp3goo.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/bad-meets-evil-lighters.jpg")
Track.create(user_id: 1, title: "Shape of You", artist: "Ed Sheeran", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Ed_Sheeran_-_Shape_Of_You_Official_Lyric_Video.imack_.co_.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/ed-sheeran-shape-of-you.jpg")
Track.create(user_id: 1, title: "Shape of You (NOTD Remix)", artist: "Ed Sheeran", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Ed+Sheeran+-+Shape+of+You+(NOTD+Remix).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/ed-sheeran-shape-of-you-notd.jpg")
Track.create(user_id: 1, title: "Photograph (Acoustic)", artist: "Ed Sheeran", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Ed+Sheeran+-+Photograph+(Acoustic+Version)+(mp3goo.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/ed-sheeran-photograph.jpg")
Track.create(user_id: 1, title: "Different Skies", artist: "Shoffy", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Different+Skies+(mp3goo.com).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/shoffy-different-skies.jpg")
Track.create(user_id: 1, title: "That's What I Like", artist: "Bruno Mars", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Bruno+Mars++That's+What+I+Like+%5B24K+MAGIC%5D+-+Lyric+Video.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/bruno-mars-thats-what-i-like.jpg")
Track.create(user_id: 1, title: "All Time Low", artist: "Jon Bellion", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/All+Time+Low+By+Jon+Bellion+(Lyrics).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/jon-bellion-all-time-low.png")
Track.create(user_id: 1, title: "Falling", artist: "Alesso", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Alesso+-+Falling.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/alesso-falling.jpg")
Track.create(user_id: 1, title: "Scars To Your Beautiful", artist: "Alessia Cara", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/Alessia+Cara+-+Scars+To+Your+Beautiful+(NOTD+Remix++Audio).mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/alessia-cara-scars.png")
Track.create(user_id: 1, title: "Paris", artist: "The Chainsmokers", track_url:"https://s3-us-west-1.amazonaws.com/eden-audio/tracks/%5BLyrics%2BVietsub%5D+Paris+-+The+Chainsmokers.mp3", img_url:"https://s3-us-west-1.amazonaws.com/eden-audio/track_images/the-chainsmokers-paris.jpeg")
